export const ADD_TIMESHEET = "ADD_TIMESHEET";
export const DELETE_TIMESHEET = "DELETE_TIMESHEET";
export const UPDATE_TIMESHEET = "UPDATE_TIMESHEET";
export const FILTER_TIMESHEET = "FILTER_TIMESHEET";
export const SET_CURRENT = "SET_CURRENT";
export const CLEAR_CURRENT = "CLEAR_CURRENT";
export const CLEAR_FILTER = "CLEAR_FILTER";
